<?xml version="1.0" encoding="UTF-8"?><testrun name="OrderServiceTest" project="mocking_homework1" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="pl.luciow.warehouse.OrderServiceTest" time="0.144">
    <testcase name="processPaymentSuccessTest" classname="pl.luciow.warehouse.OrderServiceTest" time="0.116"/>
    <testcase name="processPaymentThrowTest" classname="pl.luciow.warehouse.OrderServiceTest" time="0.001"/>
    <testcase name="fillOrderSuccesTest" classname="pl.luciow.warehouse.OrderServiceTest" time="0.005"/>
    <testcase name="cancelOrderTest" classname="pl.luciow.warehouse.OrderServiceTest" time="0.021">
      <failure>org.mockito.exceptions.verification.NeverWantedButInvoked: 
warehouseImpl.addItems(&lt;any&gt;);
Never wanted here:
-&gt; at pl.luciow.warehouse.OrderServiceTest.cancelOrderTest(OrderServiceTest.java:118)
But invoked here:
-&gt; at pl.luciow.warehouse.impl.OrderServiceImpl.cancelOrder(OrderServiceImpl.java:53)
&#13;
	at pl.luciow.warehouse.OrderServiceTest.cancelOrderTest(OrderServiceTest.java:118)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)&#13;
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)&#13;
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)&#13;
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)&#13;
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)&#13;
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)&#13;
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)&#13;
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)&#13;
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="fillOrderThrowTest" classname="pl.luciow.warehouse.OrderServiceTest" time="0.001"/>
  </testsuite>
</testrun>
